### ISSUE TITLE
Roadmap del contenido de las clases

### ISSUE THREAD

**Issue by Krax7** [devfmx/master-data-ai#30]
Etapas:
- [x] Contenido organizado en Google Drive
- [ ] Lecturas en Campus con breve resumen del tema y links a presentaciones y colabs
- [ ] Migrar contenido de presentaciones a lecturas
  - [ ] Generar con base en plantilla y/o formato de la lectura
  - [ ] Almacenar imágenes y GIFs en storage de GCP
- [ ] Migrar colabs teóricos a replits dentro de Campus
- [ ] Migrar colabs de challenge a katas dentro de Campus
